# Generated by Django 4.2.7 on 2025-06-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_hub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="last_message_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
