# Generated by Django 4.2.7 on 2025-06-26 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_hub", "0002_alter_conversation_last_message_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
