# Generated by Django 4.2.22 on 2025-06-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agent_hub", "0003_alter_conversation_created_at"),
        ("agent_hub", "0003_create_default_user_groups"),
    ]

    operations = []
