# Generated by Django 4.2.7 on 2025-06-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaccount",
            name="inbound_channel",
            field=models.CharField(
                choices=[("smtp", "SMTP"), ("imap", "IMAP")],
                default="imap",
                help_text="Service for receiving messages",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emailaccount",
            name="outbound_channel",
            field=models.CharField(
                choices=[("smtp", "SMTP"), ("imap", "IMAP")],
                default="smtp",
                help_text="Service for sending messages",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("error", "Error"),
                    ("maintenance", "Maintenance"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
    ]
