# Generated by Django 4.2.7 on 2025-06-26 15:18

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_integration", "0002_emailaccount_inbound_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="incoming_password",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=500)),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="smtp_password",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=500)),
        ),
    ]
