# Generated by Django 4.2.7 on 2025-06-27 04:16

from django.db import migrations, models

import email_integration.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("email_integration", "0003_alter_emailaccount_incoming_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="incoming_password",
            field=email_integration.models.fields.EncryptedCharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="max_emails_per_poll",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="smtp_password",
            field=email_integration.models.fields.EncryptedCharField(max_length=1000),
        ),
    ]
