# Generated by Django 4.2.7 on 2025-06-26 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppBusinessAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("business_account_id", models.CharField(max_length=100, unique=True)),
                ("phone_number_id", models.CharField(max_length=100, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("display_phone_number", models.CharField(max_length=20)),
                ("access_token", models.TextField()),
                ("webhook_verify_token", models.CharField(max_length=100)),
                ("app_id", models.CharField(max_length=100)),
                ("app_secret", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("rate_limit_per_second", models.IntegerField(default=10)),
                ("rate_limit_per_hour", models.IntegerField(default=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "whatsapp_business_accounts",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wa_id", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20)),
                ("profile_name", models.CharField(blank=True, max_length=200)),
                ("is_business_verified", models.BooleanField(default=False)),
                ("is_opted_in", models.BooleanField(default=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="whatsapp_integration.whatsappbusinessaccount",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_contacts",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_contacts",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wa_message_id", models.CharField(max_length=100, unique=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=20,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("sticker", "Sticker"),
                            ("location", "Location"),
                            ("contacts", "Contacts"),
                            ("template", "Template"),
                            ("interactive", "Interactive"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("media_url", models.URLField(blank=True)),
                ("media_id", models.CharField(blank=True, max_length=100)),
                ("media_filename", models.CharField(blank=True, max_length=255)),
                ("media_mime_type", models.CharField(blank=True, max_length=100)),
                ("media_sha256", models.CharField(blank=True, max_length=64)),
                ("media_size", models.BigIntegerField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="whatsapp_integration.whatsappbusinessaccount",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="whatsapp_integration.whatsappcontact",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_messages",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_id", models.CharField(max_length=100, unique=True)),
                ("file_path", models.FileField(upload_to="whatsapp/media/")),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("file_size", models.BigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("is_downloaded", models.BooleanField(default=False)),
                ("download_url", models.URLField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="whatsapp_integration.whatsappbusinessaccount",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="whatsapp_integration.whatsappmessage",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_media_files",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("messages", "Messages"),
                            ("message_status", "Message Status"),
                            ("account_alerts", "Account Alerts"),
                            (
                                "business_capability_update",
                                "Business Capability Update",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("webhook_id", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField(default=dict)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="whatsapp_integration.whatsappbusinessaccount",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_webhook_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["processing_status", "-created_at"],
                        name="whatsapp_we_process_cad246_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="whatsapp_we_event_t_053ffa_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("disabled", "Disabled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("authentication", "Authentication"),
                            ("marketing", "Marketing"),
                            ("utility", "Utility"),
                        ],
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="en_US", max_length=10)),
                ("components", models.JSONField(default=list)),
                ("quality_score", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="whatsapp_integration.whatsappbusinessaccount",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_templates",
                "unique_together": {("business_account", "name", "language")},
            },
        ),
        migrations.CreateModel(
            name="WhatsAppRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=100)),
                ("request_count", models.IntegerField(default=0)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("is_blocked", models.BooleanField(default=False)),
                ("reset_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_limits",
                        to="whatsapp_integration.whatsappbusinessaccount",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_rate_limits",
                "unique_together": {("business_account", "endpoint", "window_start")},
            },
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["contact", "-timestamp"], name="whatsapp_me_contact_6878cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["status", "-timestamp"], name="whatsapp_me_status_e16a79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["direction", "-timestamp"],
                name="whatsapp_me_directi_66aa9f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="whatsappcontact",
            unique_together={("business_account", "wa_id")},
        ),
    ]
